### ISSUE TITLE
Task assignment should not be accessible when you're unauthenticated

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#1081]
The task assignment should not be accessible when you're unauthenticated, but it apparently is accessible when you're not logged in.

https://sentry.io/code-corps/code-corps-ember/issues/222617837/

```
Error: Ember Data Request POST https://api.codecorps.org/user-tasks returned a 401
Payload (application/json; charset=utf-8)
[object Object]
  at comparableMoment (moment/index.js:58)
  at comparableMoment (moment/index.js:58)
  at comparableMoment (moment/index.js:58)
  at update (bower_components/ember/ember.prod.js:41934)
  at comparableMoment (moment/index.js:58)
...
(6 additional frame(s) were not displayed)
```

**Comment by jderr-mx** [comment]
@JoshSmith When you get a chance fill me in on how it should work. 
I am going to assume that projects should be visible when not logged in?
So this url should work
`/code-corps/code-corps`
but not 
`/code-corps/code-corps/tasks`

Also hide the tasks link from the project page since tasks should not be visible. 
Where should they be redirected should they go to the tasks url, login? the project page?

**Comment by JoshSmith** [comment]
The issue here is that when you navigate to tasks you see the following:

![](https://cl.ly/2z0T0z433k1Y/Screen%20Shot%202017-03-06%20at%207.35.46%20PM.png)

If you're neither authenticated nor able to assign tasks, this link should not be hoverable nor clickable, and should not show a dropdown arrow.
