### ISSUE TITLE
During task assignment, search should also filter by organization

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1088]
# Problem

Not sure if we actually want this behavior, but it makes sense with everything else.

Right now, the initial user dropdown for task assignment shows organization members.
Once we start searching, though, it queries users by query term alone, so the results will not be constrained to the organization.

I think this should not be the case. We should constrain results by organization.

**Comment by JoshSmith** [comment]
This is not actually how I think we want this to work. We want the default list of users to be all members for easy assignment within the project, but then be able to assign people outside the project. Eventually I would like for task assignment to be something that even has a status associated with it, so that if the person is not in the organization and you assign them, it creates a join request for the person. Similarly someone could join and assign themselves a task when they request membership that's granted when they're approved to the project. One of my big frustrations with GitHub is how slow the onboarding process of task assignment can be, and this proposal mitigates some of that.
