### ISSUE TITLE
Erasing a project description doesn't work as expected

### ISSUE THREAD

**Issue by rickr** [code-corps/code-corps-ember#1155]
# Problem

Steps to rep:
* As an owner visit the project page (https://www.codecorps.org/operation-code/operation-code)
* Edit the description, enter some text, click save.
* Confirm the text appears in the description.
* Edit the description and remove all text, click save.
* Confirm the description remains the same.
* Edit the description.
* Confirm the text box is empty.
* Enter a space, click save.
* Confirm the description reverts to its original state

I expected that removing all text would remove the description.

**Comment by JoshSmith** [comment]
@rickr I think the reasoning here on the API was that a `description` could only be changed to another description and not removed altogether, otherwise the project card on the projects page (and other UI elements) would be entirely empty in those areas.

If we simply told you that this was the case (with some sort of an error state in the UI), would that help? Or would you still want to be able to clear the description entirely?

**Comment by JoshSmith** [comment]
My comment above is incorrect. I believe that this is an unintended bug affecting the `long-description-markdown`, and may be due to the way that we're currently handling what attributes are passed to the API.

**Comment by JoshSmith** [comment]
@begedin could use your thoughts on this one.
