### ISSUE TITLE
Dry up containsCode logic

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#131]
There is some duplication in the `containsCode` logic in the comment and post models. I'm also not sure if this is the best way to be handling this, or if there's something that can be done server-side. For now, it works.

**Comment by idelairre** [comment]
How about a mixin?

Also, I just took a whack at this using `includes` instead of `indexOf` and Phantomjs threw an error. I'm pretty sure this is because phantom hasn't implemented it yet. `includes` is more expressive but I'm not sure the best way to go about polyfilling Phantomjs or if its worth it.

In the mean time, I can just submit a PR for a mixin using `indexOf`.

**Comment by JoshSmith** [comment]
@idelairre that sounds like a pretty good approach to me, so long as we can unit test the mixin, as well!
