### ISSUE TITLE
Archive a task

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#1408]
# Problem

We should add a button to the task page that allows you to archive the task.

**Comment by begedin** [comment]
~1 hour for the button and the action 
  - simple, set's property `archived: true`, saves
  - shown if not archived, not shown otherwise
~ 1 hour for tests
   - acceptance: "user can archive a task"
   - integration: "clicking archive button calls function"
   - integration: "archive button is hidden if task is already archived"

**Comment by JoshSmith** [comment]
Closed by #1505
