### ISSUE TITLE
Task data should reload whenever reloading the task board

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#1418]
# Problem

The task board has data that is changing often. Whenever the Tasks tab is loaded on the project page, the latest task data should be reloaded from the API.

**Comment by begedin** [comment]
The cause, I assume, would be the `model` hook

```Ember
async model() {
  let project = this.modelFor('project');
  let memberPromises = await get(project, 'projectUsers').then((projectUsers) => {
    return projectUsers.map((projectUser) => get(projectUser, 'user'));
  });
  return RSVP.hash({ project, members: RSVP.all(memberPromises) });
},
```

- the `async` and `await` we have there serve no real purpose, since we still wait for those to resolve, `then` do something. I'd just remove them
- the tasks/task lists aren't reloading because we just use `this.modelFor('project')`. In order to trigger a reload, we would have to revisit the base project route at `/:organization_slug/:project_slug/`. The simplest solution would be to copy the model hook from `routes/project.js` and work from there:

```Ember
get(this, 'store').queryRecord('project', {
  slug: params.project_slug,
  sluggedRouteSlug: params.slugged_route_slug
}, { reload: true }).then((project) => {
  let memberPromises = get(project, 'projectUsers').then((projectUsers) => {
    return projectUsers.map((projectUser) => get(projectUser, 'user'));
  });
  return RSVP.hash({ project, members: RSVP.all(memberPromises) });
});
```

That being said, this reeks of hacky. My prefered solution, if we need the project, would be to either 
- just query for and assign the project as the model, then have the task lists and the project users be a computed on the controller
- get the project using `modelFor`, then have the model hook explicitly make two queries, one for all members of that project, the other for all task lists of that project. our API would need to support those filters on those respective endpoints

I would say the assessment is

- hacky solution ~1 hour, keeping in mind we will likely be going back to this in the future
- first non-hacky solution (query for project) ~2-4 hours, depending on tests, etc
- second non-hacky solution ~4-6 hours

**Comment by JoshSmith** [comment]
Okay, I think we probably need to discuss this further so I fully understand what's happening here and why the non-hacky solutions are so deeply involved.
