### ISSUE TITLE
Individual task page should force reload data

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#1419]
# Problem

Each `tasks/:id` page has a lot of dynamic data on it that changes frequently. When loading this page for a second time, that data should reload from the API.

**Comment by begedin** [comment]
Trying this out on the client, here's the behavior I'm observing:

- Start on the homepage -> click CodeCorps -> project loads -> click task 48 -> task loads from api
- From task 48 page -> click "Tasks" on tab -> task lists  do not reload -> click task 48 -> task loads from api
- From task 48 page -> hit "Back" in browser UI -> task lists do not reload -> click "Forward" -> task loads from api
- From task 48 page -> hit "Back" in browser UI -> tasks lists do not reload -> click task 48 -> task loads from api

From my POV, the `/:organization_slug/:project_slug/tasks/:number` is not the issue. The  `/:organization_slug/:project_slug/tasks/`route is the problem.

The cause, I assume, would be the `model` hook

```Ember
async model() {
  let project = this.modelFor('project');
  let memberPromises = await get(project, 'projectUsers').then((projectUsers) => {
    return projectUsers.map((projectUser) => get(projectUser, 'user'));
  });
  return RSVP.hash({ project, members: RSVP.all(memberPromises) });
},
```

- the `async` and `await` we have there serve no real purpose, since we still wait for those to resolve, `then` do something. I'd just remove them
- the tasks/task lists aren't reloading because we just use `this.modelFor('project')`. In order to trigger a reload, we would have to revisit the base project route at `/:organization_slug/:project_slug/`. The simplest solution would be to copy the model hook from `routes/project.js` and work from there:

```Ember
get(this, 'store').queryRecord('project', {
  slug: params.project_slug,
  sluggedRouteSlug: params.slugged_route_slug
}, { reload: true }).then((project) => {
  let memberPromises = get(project, 'projectUsers').then((projectUsers) => {
    return projectUsers.map((projectUser) => get(projectUser, 'user'));
  });
  return RSVP.hash({ project, members: RSVP.all(memberPromises) });
});
```

That being said, this reeks of hacky. My prefered solution, if we need the project, would be to either 
- just query for and assign the project as the model, then have the task lists and the project users be a computed on the controller
- get the project using `modelFor`, then have the model hook explicitly make two queries, one for all members of that project, the other for all task lists of that project. our API would need to support those filters on those respective endpoints

I would say the assessment is

- hacky solution ~1 hour, keeping in mind we will likely be going back to this in the future
- first non-hacky solution (query for project) ~2-4 hours, depending on tests, etc
- second non-hacky solution ~4-6 hours

**Comment by JoshSmith** [comment]
I was not positive whether this was happening but I think this is clear that it is not.

The `project/tasks/task` route does the following in the `model` hook: `return store.queryRecord('task', { projectId, number });`

I'm assuming this fetches fresh data every time.
