### ISSUE TITLE
Add terms of service

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#184]
We just need this to be designed in HTML/CSS, and then plug in the values.

![](https://s3.amazonaws.com/f.cl.ly/items/0I1W270S253r0l1a322C/Screen%20Shot%202016-06-20%20at%2012.43.04%20PM.png?v=986f3a0d)

**Comment by JoshSmith** [comment]
In addition to the relatively boilerplate Terms of Use that are good to have:

Would it make sense in the terms to adopt language similar to the contributor convenant? Would it be reasonable to apply this language to projects on the platform?
http://contributor-covenant.org/version/1/4/

I would like to mention that projects are expected to adopt open source licensing. The type of licensure is up to the project maintainers but the platform is not intended to be used for the organization or distribution of closed source software. Also ensure that no one is infringing on anyone else’s IP.

Want to mention that we collect and analyze data in order to improve the service. That data will never be made available to third parties.

Want to mention our forthcoming GitHub integration, which is used to provide the service.

Want to mention the funding aspects, including that we use Stripe to collect credit card information and do not store the actual card information on our own servers.

Want to also mention that funding projects is at the risk of the individual, but that project maintainers need to make good faith efforts to explain how funds will be spent, how they have been spent, what they are working on and what they expect to work on.

Project maintainers should aim for a level of transparency in their maintenance of projects that does not bring undue risk upon themselves (the latter part of this is important, as Gratipay was rightly called out for being over-transparent by sharing open video calls with people that did not appreciate that).

Funds are provided to projects immediately and distribution of those funds is up to the responsibility of the maintainers. As of right now, we have no way of facilitating tax-deductible donations to eligible organizations like 501(c)(3)s.

Should let it be known that donating to projects is subject to a transaction fee for service processing and that we also implement a transaction fee for maintaining our own overhead and providing support to project maintainers.

**Comment by christopherstyles** [comment]
I would definitely agree with having language like the [Contributor Covenant](http://contributor-covenant.org/version/1/4/) here, I think it goes a long way in signalling a welcoming and positive collaboration space. :+1:

**Comment by JoshSmith** [comment]
Yeah, I think rephrasing the language to be more like a terms of use and calling out that we've adapted it in the sidebar would be good.

**Comment by ethantanner** [comment]
The additions look solid, I also agree about adopting language similar to the Contributor Covenant.

**Comment by olegko** [comment]
Don't see anything wrong with Contributor Covenant. I agree with @christopherstyles that it would help with creating a positive atmosphere.

"Want to mention that we collect and analyze data in order to improve the service. That data will never be made available to third parties." Which data? maybe "sold" instead of "made available"? In general, we need to consider the privacy policy (what is info is private vs public). We use 3rd parties (e.g. github, stripe, analytics) so don't want to exclude stuff like that.

I like the way kickstarter has their TOS - https://www.kickstarter.com/terms-of-use [easy to understand language, highlight paragraph at the top that explains each section]
GoFundMe has some things to consider: https://www.gofundme.com/terms
- Projects that aren't allowed
- Your Registration Obligation

https://www.indiegogo.com/about/terms also has good tos [all dated updates at the bottom - can see how the tos evolved as problems arose]. So we could/should modify the TOS as needed.

**Comment by hbrysiewicz** [comment]
I strongly support the Contributor Covenant. I'm not especially knowledgable on other terms of service but being clear about privacy and fostering a positive environment for contributors as well as maintainers is important. All points covered look good and I cannot think of anything else to consider at this time.

**Comment by whatwillb** [comment]
I absolutely agree with having language like the Contributor Covenant. Its a code of conduct, mission statement and pledge of allegiance all in one. Helps people feel the nobility in what they are doing, and also makes people have a little bit more reverence for their responsibilities to the projects and to the efforts they are supporting

**Comment by JoshSmith** [comment]
Thanks @christopherstyles, @ethantanner, @olegko, @hbrysiewicz and @whatwillb. Really glad to hear everyone is especially onboard with Contributor Covenant.
