### ISSUE TITLE
Add QA checklist for testing staging

### ISSUE THREAD

**Issue by elbeezy** [code-corps/code-corps-ember#300]
There's not much information readily available regarding the staging environment. This will be especially useful for testing the onboarding flow without spamming a bunch of dummy users into production.

**Comment by JoshSmith** [comment]
@elbeezy would you prefer this to be in the various READMEs on the projects? If I had to guess, I would say this maybe belongs at the GitHub level rather than the Code Corps level for now. I'd like if it we had some sort of per-project onboarding documentation for new users, kind of an onboarding flow. If you joined a project with some set of skills, we'll show you different onboarding steps based on that.
