### ISSUE TITLE
Handle 401 unauthorized better

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#50]
Should we be logging users out anytime they hit a `401`? Right now I see that when adding a new post, I get logged out of the application if I didn't have permission to do so. This seems unexpected. Not that I should see the form if I didn't have permission. But I'm not sure this is expected behavior.

What do you think @begedin?

**Comment by begedin** [comment]
I'm not even sure where the behavior is coming from, but no, I don't think we should be getting logged out in that case.

**Comment by begedin** [comment]
The behavior is coming from the `DataAdapterMixin` provided by `ember-simple-auth`

https://github.com/simplabs/ember-simple-auth/blob/master/addon/mixins/data-adapter-mixin.js#L97

I guess the solution is to customize the mixin. We're using the mixin by adding it inside our application adapter.

https://github.com/code-corps/code-corps-ember/blob/develop/app/adapters/application.js

**Comment by green-arrow** [comment]
@JoshSmith @begedin - I would suggest changing the response code from the API to be a 403 instead of a 401. A 401 status code generally refers to authentication status, not authorization, which is what is being described here.

I like this explanation / reasoning: http://www.dirv.me/blog/2011/07/18/understanding-403-forbidden/index.html

**Comment by JoshSmith** [comment]
Closed by https://github.com/code-corps/code-corps-api/issues/385
