### ISSUE TITLE
Link to sqashing guide in CONTRIBUTING.md is broken

### ISSUE THREAD

**Issue by Roshanjossey** [code-corps/code-corps-ember#561]
# Problem

There is an link in CONTRIBUTING.md to learn about squashing commits. This points to `https://github.com/code-corps/code-corps-ember/blob/develop/.github/docs/SQUASHING.md`.
That file doesn't exist in that path.

## Possible solutions

- [ ] Add squashing guide back in that path

- [ ] Correct the link to right path if it exists in this repo

- [ ] Change the link to a good resource. Maybe `https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History`

**Comment by rileytaylor** [comment]
I'm currently refactoring this file. CONTRIBUTING.md changed locations so the relative link is no longer correct, which is why it doesn't work. I'll go ahead and fix this while I'm at it.

The SQUASHING.md goes over most of the process for the link you suggested since we prefer rebases on origin/develop rather than HEAD (unless its a fork), but I was considering adding a link to that guide in SQUASHING for those interested in the gritty details.
