### ISSUE TITLE
Discuss didInitAttrs

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#83]
@begedin I saw throughout some places the usage of `didInitAttrs` rather than initializing with a property in the object hash of a component. What's the reasoning behind this approach?

Looping in @hbrysiewicz, as well.

**Comment by begedin** [comment]
https://vimeo.com/148529508

It's a combination of the first and the lifecycle hooks part of the video.

Setting data in `init` or `didinitAttrs` ensures different instances of components keep a state independent from each other. Doing in the hash wouldn't really make a difference in most our cases, I think, but it just seems like good practice not to do it in the hash, to avoid unexpected behavior.

**Comment by begedin** [comment]
To revisit this, I believe components should all get initialized in the `init` callback, not `didInitAttrs` (that part was a mistake on my part), unless there's a specific reason not to do that. Otherwise, we risk getting weird singleton-like behaviour with some stuff. The links in my previous comment explain that, to a degree.

https://poteto.github.io/component-best-practices/#/leaky is more specific.

**Comment by JoshSmith** [comment]
@begedin but does this only apply to arrays and objects? The example indicates that it does.

So to take an example from our code:

```javascript
export default Ember.Component.extend({
  classNames: ['editor-with-preview'],
  classNameBindings: ['mode'],

  mode: null,

  editing: Ember.computed.equal('mode', 'editing'),
  previewing: Ember.computed.equal('mode', 'previewing'),

  didInitAttrs() {
    this._super(...arguments);
    this.mode = 'editing';
  }
});
```

I would think that the `didInitAttrs()` here is superfluous, and that you could simply do `mode: 'editing'` to begin with.

Am I reading this wrong?

**Comment by begedin** [comment]
You are reading it right. With strings, it's not really a problem. However, as an example, let's say we have a component with a collection property (just plain array).

```Javascript
export default Ember.Component.extend({
  items: [itemA, itemB, itemC]
});
```

Say the components template just lists the items. Say we have two of these components on the page and then use an action to push an item into one of them. The item will appear in both components.

However, if we move that into an `init()` call, then this will not be a problem anymore.

As I said, with strings, this isn't really an issue, I believe, but it's a good overall guideline to just put stuff like that into `init()` (not `didInitAttrs()`, since that's not the intent of that callback).

**Comment by JoshSmith** [comment]
This discussion is pretty clear now and I think we're not doing anything counter to this. Closing for sanity's sake.
